import { User } from '../types/user';
import { Complaint } from '../types/complaint';
import { AppNotification } from '../types/notification';
import { ComplaintFeedback } from '../types/feedback';
import { calculateSlaDeadline } from './slaService';

export const MOCK_USERS: Record<string, User> = {
  chandani: {
    id: 'user-chandani-1',
    name: 'Chandani Chaurasiya',
    email: 'chandani.chaurasiya.sot25@gmail.com',
    role: 'STUDENT',
    studentId: 'STU-2025-SOT',
    phone: '+1 (555) 349-8821',
    department: 'School of Technology',
  },
  student: {
    id: 'user-chandani-1',
    name: 'Chandani Chaurasiya',
    email: 'chandani.chaurasiya.sot25@gmail.com',
    role: 'STUDENT',
    studentId: 'STU-2025-SOT',
    phone: '+1 (555) 349-8821',
    department: 'School of Technology',
  },
  faculty: {
    id: 'user-fac-1',
    name: 'Prof. Elena Vasquez',
    email: 'elena.vasquez@faculty.campuscare.edu',
    role: 'FACULTY',
    phone: '+1 (555) 782-9912',
    department: 'Electrical Engineering',
  },
  admin: {
    id: 'user-adm-1',
    name: 'Dean Jordan Lee',
    email: 'jordan.lee@admin.campuscare.edu',
    role: 'ADMIN',
    phone: '+1 (555) 901-4433',
    department: 'Campus Operations & Facilities',
  },
};

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-101',
    ticketNumber: 'CC-2024-00101',
    title: 'Water leakage in 2nd Floor Men\'s Washroom',
    description: 'Main pipe valve under the center sink is continuously leaking water, flooding the washroom tiles and creating a slip hazard.',
    category: 'WASHROOM',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    location: {
      building: 'Engineering Block A',
      floor: '2nd Floor',
      roomArea: 'Room A-212 Restroom',
    },
    evidence: [
      {
        id: 'ev-1',
        uri: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
        type: 'image',
        name: 'leaking-pipe.jpg',
      },
    ],
    isAnonymous: false,
    createdBy: {
      id: 'user-chandani-1',
      name: 'Chandani Chaurasiya',
      role: 'STUDENT',
      email: 'chandani.chaurasiya.sot25@gmail.com',
    },
    assignedDepartmentId: 'dept-maint',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Carlos Ruiz',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(1),
    slaTargetHours: 12,
    slaDeadline: calculateSlaDeadline(hoursAgo(6), 'HIGH').toISOString(),
    timeline: [
      {
        id: 'tl-1',
        status: 'SUBMITTED',
        timestamp: hoursAgo(6),
        actorName: 'Chandani Chaurasiya',
        actorRole: 'Student',
        comment: 'Complaint logged with high priority due to flooding risk.',
      },
      {
        id: 'tl-2',
        status: 'UNDER_REVIEW',
        timestamp: hoursAgo(5.2),
        actorName: 'Dean Jordan Lee',
        actorRole: 'Admin',
        comment: 'Verified severity. Dispatching plumbing team.',
      },
      {
        id: 'tl-3',
        status: 'ASSIGNED',
        timestamp: hoursAgo(4),
        actorName: 'Dean Jordan Lee',
        actorRole: 'Admin',
        comment: 'Assigned to Carlos Ruiz (Senior Plumber).',
      },
      {
        id: 'tl-4',
        status: 'IN_PROGRESS',
        timestamp: hoursAgo(1),
        actorName: 'Carlos Ruiz',
        actorRole: 'Staff',
        comment: 'Turned off main riser valve; replacing ruptured copper gasket.',
      },
    ],
    internalNotes: [
      {
        id: 'note-1',
        authorId: 'staff-2',
        authorName: 'Carlos Ruiz',
        text: 'Requisitioned 2x 3/4-inch brass couplings from maintenance depot.',
        createdAt: hoursAgo(1),
      },
    ],
    followersCount: 4,
  },
  {
    id: 'cmp-102',
    ticketNumber: 'CC-2024-00102',
    title: 'Ceiling Projector HDMI Port Dead in Seminar Hall 3',
    description: 'The ceiling mounted Panasonic projector does not receive HDMI signals from the presenter podium. Classes cannot project slides.',
    category: 'CLASSROOM',
    priority: 'HIGH',
    status: 'ASSIGNED',
    location: {
      building: 'Science Block B',
      floor: '1st Floor',
      roomArea: 'Seminar Hall B-104',
    },
    evidence: [],
    isAnonymous: false,
    createdBy: {
      id: 'user-fac-1',
      name: 'Prof. Elena Vasquez',
      role: 'FACULTY',
      email: 'elena.vasquez@faculty.campuscare.edu',
    },
    assignedDepartmentId: 'dept-it',
    assignedStaffId: 'staff-6',
    assignedStaffName: 'Rajesh Kumar',
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(2),
    slaTargetHours: 12,
    slaDeadline: calculateSlaDeadline(hoursAgo(8), 'HIGH').toISOString(),
    timeline: [
      {
        id: 'tl-201',
        status: 'SUBMITTED',
        timestamp: hoursAgo(8),
        actorName: 'Prof. Elena Vasquez',
        actorRole: 'Faculty',
        comment: 'Submitted prior to afternoon lectures.',
      },
      {
        id: 'tl-202',
        status: 'UNDER_REVIEW',
        timestamp: hoursAgo(6),
        actorName: 'Dean Jordan Lee',
        actorRole: 'Admin',
        comment: 'Scheduled for immediate AV diagnostics.',
      },
      {
        id: 'tl-203',
        status: 'ASSIGNED',
        timestamp: hoursAgo(2),
        actorName: 'Sarah Connor',
        actorRole: 'IT Lead',
        comment: 'Assigned to Rajesh Kumar (AV Specialist).',
      },
    ],
    internalNotes: [
      {
        id: 'note-201',
        authorId: 'user-adm-1',
        authorName: 'Dean Jordan Lee',
        text: 'Exam scheduled in this room tomorrow morning at 9 AM.',
        createdAt: hoursAgo(4),
      },
    ],
    followersCount: 7,
  },
  {
    id: 'cmp-103',
    ticketNumber: 'CC-2024-00103',
    title: 'Main Transformer Sparking near East Gate',
    description: 'Loud buzzing and visible sparks observed near the 440V step-down transformer cage beside the student parking lot.',
    category: 'ELECTRICITY',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    location: {
      building: 'Open Campus Grounds',
      floor: 'Open Campus Grounds',
      roomArea: 'East Gate Substation Enclosure',
    },
    evidence: [],
    isAnonymous: false,
    createdBy: {
      id: 'user-chandani-1',
      name: 'Chandani Chaurasiya',
      role: 'STUDENT',
      email: 'chandani.chaurasiya.sot25@gmail.com',
    },
    assignedDepartmentId: 'dept-elec',
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Arthur Jenkins',
    createdAt: hoursAgo(2.5),
    updatedAt: hoursAgo(0.5),
    slaTargetHours: 4,
    slaDeadline: calculateSlaDeadline(hoursAgo(2.5), 'CRITICAL').toISOString(),
    timeline: [
      {
        id: 'tl-301',
        status: 'SUBMITTED',
        timestamp: hoursAgo(2.5),
        actorName: 'Chandani Chaurasiya',
        actorRole: 'Student',
        comment: 'Urgent emergency complaint logged.',
      },
      {
        id: 'tl-302',
        status: 'UNDER_REVIEW',
        timestamp: hoursAgo(2.3),
        actorName: 'Dean Jordan Lee',
        actorRole: 'Admin',
        comment: 'Emergency safety alert acknowledged.',
      },
      {
        id: 'tl-303',
        status: 'ASSIGNED',
        timestamp: hoursAgo(2),
        actorName: 'Dean Jordan Lee',
        actorRole: 'Admin',
        comment: 'Immediate assignment to Arthur Jenkins & security perimeter team.',
      },
      {
        id: 'tl-304',
        status: 'IN_PROGRESS',
        timestamp: hoursAgo(0.5),
        actorName: 'Arthur Jenkins',
        actorRole: 'Chief Electrician',
        comment: 'Area cordoned off; secondary feeder isolated.',
      },
    ],
    internalNotes: [
      {
        id: 'note-301',
        authorId: 'staff-3',
        authorName: 'Arthur Jenkins',
        text: 'Insulator bushing cracked due to storm debris. Grid backup enabled.',
        createdAt: hoursAgo(0.4),
      },
    ],
    followersCount: 15,
  },
  {
    id: 'cmp-104',
    ticketNumber: 'CC-2024-00104',
    title: 'Broken Glass on Fire Exit Staircase B',
    description: 'Shattered window pane on the 3rd floor landing of Stairwell B. Glass shards on steps pose a hazard for evacuees.',
    category: 'INFRASTRUCTURE',
    priority: 'HIGH',
    status: 'RESOLVED',
    location: {
      building: 'Engineering Block A',
      floor: '3rd Floor',
      roomArea: 'Stairwell B Fire Exit',
    },
    evidence: [],
    isAnonymous: false,
    createdBy: {
      id: 'user-chandani-1',
      name: 'Chandani Chaurasiya',
      role: 'STUDENT',
      email: 'chandani.chaurasiya.sot25@gmail.com',
    },
    assignedDepartmentId: 'dept-house',
    assignedStaffId: 'staff-7',
    assignedStaffName: 'Elena Rostova',
    createdAt: hoursAgo(28),
    updatedAt: hoursAgo(4),
    resolvedAt: hoursAgo(4),
    slaTargetHours: 12,
    slaDeadline: calculateSlaDeadline(hoursAgo(28), 'HIGH').toISOString(),
    timeline: [
      {
        id: 'tl-401',
        status: 'SUBMITTED',
        timestamp: hoursAgo(28),
        actorName: 'Chandani Chaurasiya',
        actorRole: 'Student',
      },
      {
        id: 'tl-402',
        status: 'ASSIGNED',
        timestamp: hoursAgo(20),
        actorName: 'Dean Jordan Lee',
        actorRole: 'Admin',
      },
      {
        id: 'tl-403',
        status: 'IN_PROGRESS',
        timestamp: hoursAgo(10),
        actorName: 'Elena Rostova',
        actorRole: 'Staff',
      },
      {
        id: 'tl-404',
        status: 'RESOLVED',
        timestamp: hoursAgo(4),
        actorName: 'Elena Rostova',
        actorRole: 'Staff',
        comment: 'Debris completely swept and temporary acrylic safety sheet installed.',
      },
    ],
    internalNotes: [],
    feedbackId: 'fb-104',
    followersCount: 3,
  },
  {
    id: 'cmp-105',
    ticketNumber: 'CC-2024-00105',
    title: 'Wi-Fi Access Point AP-Lib-4 frequently drops connections',
    description: 'Students in the silent study zone on Floor 2 get disconnected every 5 minutes. Ping tests show 40% packet loss.',
    category: 'WIFI_INTERNET',
    priority: 'MEDIUM',
    status: 'UNDER_REVIEW',
    location: {
      building: 'Central Library',
      floor: '2nd Floor',
      roomArea: 'Silent Reading Zone 2B',
    },
    evidence: [],
    isAnonymous: false,
    createdBy: {
      id: 'user-chandani-1',
      name: 'Chandani Chaurasiya',
      role: 'STUDENT',
      email: 'chandani.chaurasiya.sot25@gmail.com',
    },
    createdAt: hoursAgo(14),
    updatedAt: hoursAgo(14),
    slaTargetHours: 24,
    slaDeadline: calculateSlaDeadline(hoursAgo(14), 'MEDIUM').toISOString(),
    timeline: [
      {
        id: 'tl-501',
        status: 'SUBMITTED',
        timestamp: hoursAgo(14),
        actorName: 'Chandani Chaurasiya',
        actorRole: 'Student',
      },
      {
        id: 'tl-502',
        status: 'UNDER_REVIEW',
        timestamp: hoursAgo(6),
        actorName: 'Sarah Connor',
        actorRole: 'IT Lead',
        comment: 'Checking RADIUS authentication server logs.',
      },
    ],
    internalNotes: [],
    followersCount: 12,
  },
  {
    id: 'cmp-106',
    ticketNumber: 'CC-2024-00106',
    title: 'Food quality & temperature in Student Canteen Counter 2',
    description: 'Warm meals served at Counter 2 were cold and undercooked today at 1:30 PM. Multiple students reported stomach cramps.',
    category: 'CANTEEN',
    priority: 'HIGH',
    status: 'SUBMITTED',
    location: {
      building: 'Central Canteen & Food Court',
      floor: 'Ground Floor',
      roomArea: 'Meal Station 2',
    },
    evidence: [],
    isAnonymous: true,
    createdBy: {
      id: 'user-chandani-1',
      name: 'Anonymous Student',
      role: 'STUDENT',
      email: 'chandani.chaurasiya.sot25@gmail.com',
    },
    createdAt: hoursAgo(1.5),
    updatedAt: hoursAgo(1.5),
    slaTargetHours: 12,
    slaDeadline: calculateSlaDeadline(hoursAgo(1.5), 'HIGH').toISOString(),
    timeline: [
      {
        id: 'tl-601',
        status: 'SUBMITTED',
        timestamp: hoursAgo(1.5),
        actorName: 'Anonymous Student',
        actorRole: 'Student',
        comment: 'Complaint filed anonymously.',
      },
    ],
    internalNotes: [],
    followersCount: 8,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-chandani-1',
    title: 'Complaint Status Updated',
    message: 'Your complaint "Water leakage in 2nd Floor Men\'s Washroom" is now IN PROGRESS.',
    type: 'STATUS_CHANGED',
    complaintId: 'cmp-101',
    read: false,
    createdAt: hoursAgo(1),
  },
  {
    id: 'notif-2',
    userId: 'user-chandani-1',
    title: 'Complaint Resolved',
    message: '"Broken Glass on Fire Exit Staircase B" has been resolved. Please share your feedback!',
    type: 'COMPLAINT_RESOLVED',
    complaintId: 'cmp-104',
    read: false,
    createdAt: hoursAgo(4),
  },
  {
    id: 'notif-3',
    userId: 'user-fac-1',
    title: 'Technician Assigned',
    message: 'Rajesh Kumar has been assigned to your projector issue in Seminar Hall 3.',
    type: 'COMPLAINT_ASSIGNED',
    complaintId: 'cmp-102',
    read: true,
    createdAt: hoursAgo(2),
  },
  {
    id: 'notif-4',
    userId: 'user-adm-1',
    title: 'Critical Emergency Ticket Logged',
    message: 'CRITICAL ticket #CC-2024-00103 "Main Transformer Sparking" requires immediate attention.',
    type: 'COMPLAINT_SUBMITTED',
    complaintId: 'cmp-103',
    read: false,
    createdAt: hoursAgo(2.5),
  },
];

export const INITIAL_FEEDBACK: ComplaintFeedback[] = [
  {
    id: 'fb-104',
    complaintId: 'cmp-104',
    userId: 'user-chandani-1',
    userName: 'Chandani Chaurasiya',
    userRole: 'Student',
    rating: 5,
    comment: 'Very fast cleanup! Thank you for prioritizing student safety in the fire staircase.',
    createdAt: hoursAgo(3.5),
  },
];
