import { Department, StaffMember } from '../types/department';

export const DEPARTMENTS: Department[] = [
  {
    id: 'dept-maint',
    name: 'Maintenance',
    code: 'MAINT',
    leadName: 'David Miller',
    email: 'maintenance@campuscare.edu',
    phone: '+1 (555) 234-1001',
    staffCount: 14,
    activeTicketsCount: 8,
    iconName: 'construct-outline',
  },
  {
    id: 'dept-elec',
    name: 'Electrical',
    code: 'ELEC',
    leadName: 'Arthur Jenkins',
    email: 'electrical@campuscare.edu',
    phone: '+1 (555) 234-1002',
    staffCount: 9,
    activeTicketsCount: 5,
    iconName: 'flash-outline',
  },
  {
    id: 'dept-it',
    name: 'IT Support',
    code: 'IT',
    leadName: 'Sarah Connor',
    email: 'itsupport@campuscare.edu',
    phone: '+1 (555) 234-1003',
    staffCount: 12,
    activeTicketsCount: 6,
    iconName: 'hardware-chip-outline',
  },
  {
    id: 'dept-house',
    name: 'Housekeeping',
    code: 'HOUSE',
    leadName: 'Elena Rostova',
    email: 'housekeeping@campuscare.edu',
    phone: '+1 (555) 234-1004',
    staffCount: 22,
    activeTicketsCount: 11,
    iconName: 'sparkles-outline',
  },
  {
    id: 'dept-sec',
    name: 'Security',
    code: 'SEC',
    leadName: 'Captain Marcus Vance',
    email: 'security@campuscare.edu',
    phone: '+1 (555) 234-1005',
    staffCount: 16,
    activeTicketsCount: 3,
    iconName: 'shield-checkmark-outline',
  },
  {
    id: 'dept-trans',
    name: 'Transport',
    code: 'TRANS',
    leadName: 'Robert Lang',
    email: 'transport@campuscare.edu',
    phone: '+1 (555) 234-1006',
    staffCount: 8,
    activeTicketsCount: 2,
    iconName: 'bus-outline',
  },
  {
    id: 'dept-admin',
    name: 'Administration',
    code: 'ADMIN',
    leadName: 'Dr. Patricia Hayes',
    email: 'admin@campuscare.edu',
    phone: '+1 (555) 234-1007',
    staffCount: 7,
    activeTicketsCount: 4,
    iconName: 'briefcase-outline',
  },
  {
    id: 'dept-lib',
    name: 'Library',
    code: 'LIB',
    leadName: 'Miriam Vance',
    email: 'library@campuscare.edu',
    phone: '+1 (555) 234-1008',
    staffCount: 6,
    activeTicketsCount: 2,
    iconName: 'book-outline',
  },
  {
    id: 'dept-cant',
    name: 'Canteen',
    code: 'CANT',
    leadName: 'Chef Gordon Patel',
    email: 'canteen@campuscare.edu',
    phone: '+1 (555) 234-1009',
    staffCount: 10,
    activeTicketsCount: 3,
    iconName: 'restaurant-outline',
  },
];

export const MOCK_STAFF: StaffMember[] = [
  { id: 'staff-1', name: 'David Miller', departmentId: 'dept-maint', role: 'Head of Facilities', email: 'd.miller@campuscare.edu', phone: '+1 555-0101' },
  { id: 'staff-2', name: 'Carlos Ruiz', departmentId: 'dept-maint', role: 'Senior Plumber', email: 'c.ruiz@campuscare.edu', phone: '+1 555-0102' },
  { id: 'staff-3', name: 'Arthur Jenkins', departmentId: 'dept-elec', role: 'Chief Electrician', email: 'a.jenkins@campuscare.edu', phone: '+1 555-0103' },
  { id: 'staff-4', name: 'Devon Miles', departmentId: 'dept-elec', role: 'HVAC Specialist', email: 'd.miles@campuscare.edu', phone: '+1 555-0104' },
  { id: 'staff-5', name: 'Sarah Connor', departmentId: 'dept-it', role: 'Network Admin', email: 's.connor@campuscare.edu', phone: '+1 555-0105' },
  { id: 'staff-6', name: 'Rajesh Kumar', departmentId: 'dept-it', role: 'AV Systems Tech', email: 'r.kumar@campuscare.edu', phone: '+1 555-0106' },
  { id: 'staff-7', name: 'Elena Rostova', departmentId: 'dept-house', role: 'Sanitation Supervisor', email: 'e.rostova@campuscare.edu', phone: '+1 555-0107' },
  { id: 'staff-8', name: 'Marcus Vance', departmentId: 'dept-sec', role: 'Chief of Safety', email: 'm.vance@campuscare.edu', phone: '+1 555-0108' },
];
